repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-ast
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black
        args: ["--line-length", "100"]
